### ISSUE TITLE
Chart linkrot

### ISSUE THREAD

**Issue by kousu** [notnami/phonemes#7]
The phonological chart is no longer at https://dl.dropboxusercontent.com/u/5956329/Riggle/PhonChart_v1212.pdf ; neither is there https://dl.dropboxusercontent.com/u/5956329/Riggle/_Riggle_CV.pdf anymore either :/

**Comment by anna-hope** [comment]
That's unfortunate. I had a version of it saved locally, so if I manage to find it, I can re-upload it and fix the link. 

Likewise, if anyone else still has the chart, please let me know or PR.

**Comment by anna-hope** [comment]
I have dug up my copy of the chart and pushed it to the repository. Probably should've done that from the beginning.

**Comment by wabmhnsbn** [comment]
Sorry to bother u, could u tell me the source paper for this chart or any other references? I need to cite it.
